// GENERATED by scripts/generate-version.mjs — do not edit by hand.
export const APP_NAME = "brainana-viewer"
export const APP_VERSION = "1.0.0"
export const BUILD_ID = "v1.0.0-28-g10feb38-10feb38"
export const versionInfo = Object.freeze({ app: APP_NAME, version: APP_VERSION, buildId: BUILD_ID })
