// End-to-end check of the assumption the report's provenance rests on: a pipeline file's JSON
// sidecar is reachable over the SAME /brainana-data route as the file itself, with no server-side
// change and no extension gating. Runs against the in-repo demo dataset (a real brainana output).
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { startServer } from '@brainana/core-server/runtime.mjs'
import { generateSessionToken } from '@brainana/core-server/security.mjs'
import { viewerManifestProvider } from '../apps/viewer/server/manifest.mjs'
import { sidecarUrl, displayPath, fetchGeneratedBy, brainanaVersion } from '../apps/viewer/src/report/provenance.ts'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const demoRoot = path.join(repoRoot, 'datasets', 'demo_viewer')

if (!fs.existsSync(path.join(demoRoot, 'sub-example'))) {
  console.log('  skip - datasets/demo_viewer not checked out')
  console.log('report_sidecar_e2e_test: skipped')
  process.exit(0)
}

let passed = 0
const ok = (name) => {
  passed++
  console.log(`  ok - ${name}`)
}

async function main() {
  const token = generateSessionToken()
  const { server, address } = await startServer({ token, port: 0, manifestProvider: viewerManifestProvider })
  const base = `http://127.0.0.1:${address.port}`
  const auth = { Authorization: `Bearer ${token}` }
  // The exact fetch shape the report uses in the browser (RuntimeClient.apiFetch).
  const apiFetch = (url) => fetch(`${base}${url}`, { headers: auth })

  try {
    const source = await (
      await fetch(`${base}/api/sources`, {
        method: 'POST',
        headers: { ...auth, 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'local', path: demoRoot, label: 'demo' }),
      })
    ).json()
    const manifest = await (await fetch(`${base}/api/sources/${source.id}/manifest/sub-example`, { headers: auth })).json()
    assert.ok(manifest.atlases.length > 0, 'the demo subject exposes atlases')
    ok('the demo dataset opens and produces a manifest')

    // --- a pipeline atlas volume: its sidecar must be fetchable over the data route ---
    const atlas = manifest.atlases.find((a) => a.volume?.endsWith('.nii.gz'))
    assert.ok(atlas, 'at least one atlas has a .nii.gz volume')
    const derived = sidecarUrl(atlas.volume)
    assert.ok(derived, 'a .nii.gz volume yields a sidecar URL')
    const res = await apiFetch(derived)
    assert.equal(res.status, 200, `the data route serves ${derived} — .json is not gated`)
    const body = await res.json()
    assert.ok(Array.isArray(body.GeneratedBy), 'the sidecar carries a GeneratedBy block')
    ok('a sidecar JSON is served over the same data route as its volume')

    // --- the full client path returns the pipeline version ---
    const entries = await fetchGeneratedBy(apiFetch, atlas.volume)
    const version = brainanaVersion(entries)
    assert.equal(version, '1.3.0', 'the demo dataset was generated by brainana 1.3.0')
    ok('fetchGeneratedBy resolves the real pipeline version end to end')

    // The same holds for a surface .func.gii, whose double extension must be stripped whole.
    const surfaceAtlas = manifest.atlases.find((a) => a.surface?.left)
    if (surfaceAtlas) {
      const surfSidecar = sidecarUrl(surfaceAtlas.surface.left)
      assert.equal((await apiFetch(surfSidecar)).status, 200, `${surfSidecar} is served`)
      ok('a .func.gii surface overlay resolves its sidecar too')
    }

    // --- FreeSurfer assets are not pipeline outputs: no sidecar must be requested for them ---
    const surface = manifest.surfaces.pial?.left ?? manifest.surfaces.white?.left
    assert.ok(surface, 'the demo subject exposes a cortical surface')
    if (!/\.gii$/i.test(surface)) {
      assert.equal(sidecarUrl(surface), null, 'an extensionless FreeSurfer surface yields no sidecar URL')
    }
    const volume = manifest.volumes.find((v) => v.url.endsWith('.mgz'))
    assert.ok(volume, 'the demo subject exposes a FreeSurfer .mgz volume')
    assert.equal(sidecarUrl(volume.url), null, 'a .mgz volume yields no sidecar URL')
    assert.deepEqual(await fetchGeneratedBy(apiFetch, volume.url), [], 'and no provenance is claimed for it')
    ok('FreeSurfer-derived assets are correctly reported as having no pipeline sidecar')

    // --- the path shown in the report is the real source-relative path ---
    const shown = displayPath(atlas.volume)
    assert.equal(shown.startsWith('/'), false, 'the displayed path is source-relative')
    assert.ok(fs.existsSync(path.join(demoRoot, shown)), `${shown} exists on disk relative to the dataset root`)
    ok('the path printed in the report resolves to the real file on disk')
  } finally {
    server.close()
  }

  console.log(`\nreport_sidecar_e2e_test: ${passed} checks passed`)
}

await main()
